// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQ2ywz-6XgCfNMrcHjcQ4SJ655rdGi58',
    appId: '1:410600043226:android:656e511cd7a534867cabe3',
    messagingSenderId: '410600043226',
    projectId: 'go-raipur',
    storageBucket: 'go-raipur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGND971zcQGNMV7HPHRgT0w5ucGfLBho',
    appId: '1:410600043226:ios:df73e543f3dd80237cabe3',
    messagingSenderId: '410600043226',
    projectId: 'go-raipur',
    storageBucket: 'go-raipur.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGND971zcQGNMV7HPHRgT0w5ucGfLBho',
    appId: '1:410600043226:ios:df73e543f3dd80237cabe3',
    messagingSenderId: '410600043226',
    projectId: 'go-raipur',
    storageBucket: 'go-raipur.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );
}
